server:
  port: 9000

# data source
spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:craftbeer
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
    h2:
        console:
            enabled: true
            path: /h2-console